### ISSUE TITLE
Cura 5.0 Update ???

### ISSUE THREAD

**Issue by PhilBaz** [dapostol73/Randoms#1]
Does this need to be updated for Cura 5.0 ???

I'm not seeing the script in Extensions > Post processing .

I'm placing it in C:\Users\xxx\AppData\Roaming\cura\master\plugins, as instructed here : [main/macros/probing/bed_mesh.cfg](https://github.com/Frix-x/klipper-voron-V2/blob/main/macros/probing/bed_mesh.cfg) .

**Comment by dapostol73** [comment]
I have it working with Cura 5.0, for that version it lives here:

C:\Program Files\Ultimaker Cura 5.0.0\share\cura\plugins\PostProcessingPlugin\scripts

**Comment by PhilBaz** [comment]
@dapostol73 

Thanks!!! works!
